/* Phosphor Icons — one icon family for the whole project. */
import {
  AirplaneLanding,
  AirplaneTakeoff,
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Building,
  CalendarBlank,
  CalendarCheck,
  Camera,
  CaretDown,
  ChartLineUp,
  ChalkboardTeacher,
  Check,
  Clock,
  Code,
  EnvelopeSimple,
  Globe,
  GraduationCap,
  Graph,
  Handshake,
  List,
  MapPin,
  Microphone,
  Phone,
  Quotes,
  ShieldCheck,
  Sparkle,
  Star,
  Trophy,
  UsersThree,
  X,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react";
import type { ComponentProps } from "react";

export type P = ComponentProps<Icon>;

export {
  AirplaneTakeoff as PlaneTakeoff,
  AirplaneLanding as PlaneLanding,
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Building,
  CalendarBlank as CalendarIcon,
  CalendarCheck,
  Camera,
  CaretDown as ChevronDown,
  ChartLineUp as ChartLine,
  ChalkboardTeacher as Chalkboard,
  Check,
  Clock,
  Code,
  EnvelopeSimple as Mail,
  Globe,
  GraduationCap as Graduate,
  Graph as Network,
  Handshake,
  List as Menu,
  MapPin,
  Microphone as Mic,
  Phone,
  Quotes as Quote,
  ShieldCheck,
  Sparkle,
  Star,
  Trophy,
  UsersThree as Users,
  X,
};

export const iconMap = {
  globe: Globe,
  plane: AirplaneTakeoff,
  handshake: Handshake,
  calendar: CalendarBlank,
  calendarCheck: CalendarCheck,
  users: UsersThree,
  mic: Microphone,
  chalkboard: ChalkboardTeacher,
  network: Graph,
  planeTakeoff: AirplaneTakeoff,
  planeLanding: AirplaneLanding,
  chart: ChartLineUp,
  graduate: GraduationCap,
  code: Code,
  shield: ShieldCheck,
  trophy: Trophy,
  building: Building,
} as const;

export type IconName = keyof typeof iconMap;
